// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtX1wlo2hdb5xj1kfiuCGU7taangPgASg',
    appId: '1:583679056577:web:67f140c3dfdaa433fc9240',
    messagingSenderId: '583679056577',
    projectId: 'katsuvideo-d77f3',
    authDomain: 'katsuvideo-d77f3.firebaseapp.com',
    databaseURL: 'https://katsuvideo-d77f3.firebaseio.com',
    storageBucket: 'katsuvideo-d77f3.appspot.com',
    measurementId: 'G-ZTQYBCSQS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtcwW9Xx3PFLG4a7ttrsDxM1-JyQU7oI',
    appId: '1:583679056577:android:03e93da508074ee2fc9240',
    messagingSenderId: '583679056577',
    projectId: 'katsuvideo-d77f3',
    databaseURL: 'https://katsuvideo-d77f3.firebaseio.com',
    storageBucket: 'katsuvideo-d77f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5WzHBffUKHXj4nMvXkMNSiR0wJIl12KY',
    appId: '1:583679056577:ios:6f1de7e08641c350fc9240',
    messagingSenderId: '583679056577',
    projectId: 'katsuvideo-d77f3',
    databaseURL: 'https://katsuvideo-d77f3.firebaseio.com',
    storageBucket: 'katsuvideo-d77f3.appspot.com',
    iosClientId: '583679056577-nmstj8kd2gfo3o336gondub243miinps.apps.googleusercontent.com',
    iosBundleId: 'com.example.katsuDojo',
  );
}
